In [1]:
import pandas as pd

df = pd.read_csv('word_population_data.csv')
df.dropna(inplace=True)

In [2]:
df

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    object
 2   Country/Territory            234 non-null    object
 3   Capital                      234 non-null    object
 4   Continent                    234 non-null    object
 5   2022 Population              234 non-null    int64
 6   2020 Population              234 non-null    int64
 7   2015 Population              234 non-null    int64
 8   2010 Population              234 non-null    int64
 9   2000 Population              234 non-null    int64
 10  1990 Population              234 non-null    int64
 11  1980 Population              234 non-null    int64
 12  1970 Population              234 non-null    int64
 13  Area (km²)                   234 non-null    int64
 14  Density (per km²)            234 non-null    float64
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(3), int64(10), object(4)
memory usage: 31.2+ KB

In [4]:
# clean the column_headers

def clean_columns_header(df):
    df.columns = df.columns.str.lower()
    df.columns = df.columns.str.strip()
    df.columns = df.columns.str.replace(" ", "_")
    return df

In [5]:
clean_columns_header(df)

,rank,cca3,country/territory,capital,continent,2022_population,2020_population,2015_population,2010_population,2000_population,1990_population,1980_population,1970_population,area_(km²),density_(per_km²),growth_rate,world_population_percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [6]:
df.columns.to_list()

['rank',
 'cca3',
 'country/territory',
 'capital',
 'continent',
 '2022_population',
 '2020_population',
 '2015_population',
 '2010_population',
 '2000_population',
 '1990_population',
 '1980_population',
 '1970_population',
 'area_(km²)',
 'density_(per_km²)',
 'growth_rate',
 'world_population_percentage']

In [7]:
numerical_data = df.select_dtypes(exclude='object').columns
categorical_data = df.select_dtypes(include='object').columns

In [8]:
numerical_data.to_list()

['rank',
 '2022_population',
 '2020_population',
 '2015_population',
 '2010_population',
 '2000_population',
 '1990_population',
 '1980_population',
 '1970_population',
 'area_(km²)',
 'density_(per_km²)',
 'growth_rate',
 'world_population_percentage']

In [9]:
categorical_data.to_list()

['cca3', 'country/territory', 'capital', 'continent']

In [10]:
## clean the content of the column

def clean_content_column(df,columns_name):
    df[columns_name] =  df[columns_name].astype(str)
    df[columns_name] =  df[columns_name].str.lower()
    df[columns_name] =  df[columns_name].str.strip()
    df[columns_name] =  df[columns_name].str.replace(" ", "")
    return df

In [11]:
for columns_name in categorical_data:
    clean_data = clean_content_column(df,columns_name)

In [12]:
for columns in numerical_data:
    df[columns] = df[columns].astype(float)

In [13]:
df

,rank,cca3,country/territory,capital,continent,2022_population,2020_population,2015_population,2010_population,2000_population,1990_population,1980_population,1970_population,area_(km²),density_(per_km²),growth_rate,world_population_percentage
0,36.0,afg,afghanistan,kabul,asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138.0,alb,albania,tirana,europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34.0,dza,algeria,algiers,africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213.0,asm,americansamoa,pagopago,oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203.0,and,andorra,andorralavella,europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226.0,wlf,wallisandfutuna,mata-utu,oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172.0,esh,westernsahara,elaaiún,africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46.0,yem,yemen,sanaa,asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63.0,zmb,zambia,lusaka,africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74.0,zwe,zimbabwe,harare,africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   rank                         234 non-null    float64
 1   cca3                         234 non-null    object
 2   country/territory            234 non-null    object
 3   capital                      234 non-null    object
 4   continent                    234 non-null    object
 5   2022_population              234 non-null    float64
 6   2020_population              234 non-null    float64
 7   2015_population              234 non-null    float64
 8   2010_population              234 non-null    float64
 9   2000_population              234 non-null    float64
 10  1990_population              234 non-null    float64
 11  1980_population              234 non-null    float64
 12  1970_population              234 non-null    float64
 13  area_(km²)                   234 non-null    float64
 14  density_(per_km²)            234 non-null    float64
 15  growth_rate                  234 non-null    float64
 16  world_population_percentage  234 non-null    float64
dtypes: float64(13), object(4)
memory usage: 31.2+ KB

In [15]:
df = df.rename(columns={'cca3': 'country_code'})

In [16]:
df

,rank,country_code,country/territory,capital,continent,2022_population,2020_population,2015_population,2010_population,2000_population,1990_population,1980_population,1970_population,area_(km²),density_(per_km²),growth_rate,world_population_percentage
0,36.0,afg,afghanistan,kabul,asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138.0,alb,albania,tirana,europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34.0,dza,algeria,algiers,africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213.0,asm,americansamoa,pagopago,oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203.0,and,andorra,andorralavella,europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226.0,wlf,wallisandfutuna,mata-utu,oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172.0,esh,westernsahara,elaaiún,africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46.0,yem,yemen,sanaa,asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63.0,zmb,zambia,lusaka,africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74.0,zwe,zimbabwe,harare,africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [17]:
df.columns.to_list()

['rank',
 'country_code',
 'country/territory',
 'capital',
 'continent',
 '2022_population',
 '2020_population',
 '2015_population',
 '2010_population',
 '2000_population',
 '1990_population',
 '1980_population',
 '1970_population',
 'area_(km²)',
 'density_(per_km²)',
 'growth_rate',
 'world_population_percentage']

In [18]:
df['capital'].iat[56]

'quito'

In [19]:
df.index

RangeIndex(start=0, stop=234, step=1)

In [20]:
df['2020_population'].loc[[0,4,8]]

0    38972230.0
4       77700.0
8    45036032.0
Name: 2020_population, dtype: float64

In [21]:
# First set the index to country_code
df = df.set_index('country_code')

In [22]:
df

,rank,country/territory,capital,continent,2022_population,2020_population,2015_population,2010_population,2000_population,1990_population,1980_population,1970_population,area_(km²),density_(per_km²),growth_rate,world_population_percentage
country_code,,,,,,,,,,,,,,,,
afg,36.0,afghanistan,kabul,asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
alb,138.0,albania,tirana,europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
dza,34.0,algeria,algiers,africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
asm,213.0,americansamoa,pagopago,oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
and,203.0,andorra,andorralavella,europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wlf,226.0,wallisandfutuna,mata-utu,oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
esh,172.0,westernsahara,elaaiún,africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
yem,46.0,yemen,sanaa,asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
zmb,63.0,zambia,lusaka,africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
zwe,74.0,zimbabwe,harare,africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [23]:
# Now we can access by country code
df.loc[['afg', 'and']].T

country_code                         afg             and
rank                                36.0           203.0
country/territory            afghanistan         andorra
capital                            kabul  andorralavella
continent                           asia          europe
2022_population               41128771.0         79824.0
2020_population               38972230.0         77700.0
2015_population               33753499.0         71746.0
2010_population               28189672.0         71519.0
2000_population               19542982.0         66097.0
1990_population               10694796.0         53569.0
1980_population               12486631.0         35611.0
1970_population               10752971.0         19860.0
area_(km²)                      652230.0           468.0
density_(per_km²)                63.0587        170.5641
growth_rate                       1.0257            1.01
world_population_percentage         0.52             0.0

In [24]:
# mutilple row and single column

df.loc[['afg','and','arm'],'capital']

country_code
afg             kabul
and    andorralavella
arm           yerevan
Name: capital, dtype: object

In [25]:
df.index

Index(['afg', 'alb', 'dza', 'asm', 'and', 'ago', 'aia', 'atg', 'arg', 'arm',
       ...
       'uzb', 'vut', 'vat', 'ven', 'vnm', 'wlf', 'esh', 'yem', 'zmb', 'zwe'],
      dtype='object', name='country_code', length=234)

In [26]:
df.columns

Index(['rank', 'country/territory', 'capital', 'continent', '2022_population',
       '2020_population', '2015_population', '2010_population',
       '2000_population', '1990_population', '1980_population',
       '1970_population', 'area_(km²)', 'density_(per_km²)', 'growth_rate',
       'world_population_percentage'],
      dtype='object')

In [27]:
df.loc[:,'2015_population']

country_code
afg    33753499.0
alb     2882481.0
dza    39543154.0
asm       51368.0
and       71746.0
          ...
wlf       12182.0
esh      491824.0
yem    28516545.0
zmb    16248230.0
zwe    14154937.0
Name: 2015_population, Length: 234, dtype: float64

In [28]:
df.iloc[1, 0:]

rank                               138.0
country/territory                albania
capital                           tirana
continent                         europe
2022_population                2842321.0
2020_population                2866849.0
2015_population                2882481.0
2010_population                2913399.0
2000_population                3182021.0
1990_population                3295066.0
1980_population                2941651.0
1970_population                2324731.0
area_(km²)                       28748.0
density_(per_km²)                98.8702
growth_rate                       0.9957
world_population_percentage         0.04
Name: alb, dtype: object

In [29]:
df.reset_index()

,country_code,rank,country/territory,capital,continent,2022_population,2020_population,2015_population,2010_population,2000_population,1990_population,1980_population,1970_population,area_(km²),density_(per_km²),growth_rate,world_population_percentage
0,afg,36.0,afghanistan,kabul,asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,alb,138.0,albania,tirana,europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,dza,34.0,algeria,algiers,africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,asm,213.0,americansamoa,pagopago,oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,and,203.0,andorra,andorralavella,europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,wlf,226.0,wallisandfutuna,mata-utu,oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,esh,172.0,westernsahara,elaaiún,africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,yem,46.0,yemen,sanaa,asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,zmb,63.0,zambia,lusaka,africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,zwe,74.0,zimbabwe,harare,africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [30]:
df.loc[df['rank']>100, 'capital']

country_code
alb            tirana
asm          pagopago
and    andorralavella
aia         thevalley
atg       saintjohn’s
            ...
ury        montevideo
vut         port-vila
vat       vaticancity
wlf          mata-utu
esh           elaaiún
Name: capital, Length: 134, dtype: object

In [31]:
df

,rank,country/territory,capital,continent,2022_population,2020_population,2015_population,2010_population,2000_population,1990_population,1980_population,1970_population,area_(km²),density_(per_km²),growth_rate,world_population_percentage
country_code,,,,,,,,,,,,,,,,
afg,36.0,afghanistan,kabul,asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
alb,138.0,albania,tirana,europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
dza,34.0,algeria,algiers,africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
asm,213.0,americansamoa,pagopago,oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
and,203.0,andorra,andorralavella,europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wlf,226.0,wallisandfutuna,mata-utu,oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
esh,172.0,westernsahara,elaaiún,africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
yem,46.0,yemen,sanaa,asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
zmb,63.0,zambia,lusaka,africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
zwe,74.0,zimbabwe,harare,africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [38]:
df[df['continent'].eq('africa')] & df['rank'].gt(100)]]

SyntaxError: unmatched ']' (803434695.py, line 1)

In [45]:
african_countries = df[df['continent'].eq('africa')]

In [46]:
rank_above_100 = df['rank'].gt(100)

In [50]:
m = african_countries[rank_above_100.reindex(african_countries.index).fillna(False)]
m

,rank,country/territory,capital,continent,2022_population,2020_population,2015_population,2010_population,2000_population,1990_population,1980_population,1970_population,area_(km²),density_(per_km²),growth_rate,world_population_percentage
country_code,,,,,,,,,,,,,,,,
bwa,144.0,botswana,gaborone,africa,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
cpv,171.0,capeverde,praia,africa,593149.0,582640.0,552166.0,521212.0,458251.0,364563.0,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
caf,117.0,centralafricanrepublic,bangui,africa,5579144.0,5343020.0,4819333.0,4660067.0,3759170.0,2809221.0,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
com,163.0,comoros,moroni,africa,836774.0,806166.0,730216.0,656024.0,536758.0,431119.0,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
dji,160.0,djibouti,djibouti,africa,1120849.0,1090156.0,1006259.0,919199.0,742033.0,577173.0,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
gnq,152.0,equatorialguinea,malabo,africa,1674908.0,1596049.0,1346973.0,1094524.0,684977.0,465549.0,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
eri,132.0,eritrea,asmara,africa,3684032.0,3555868.0,3340006.0,3147727.0,2392880.0,2149960.0,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
swz,159.0,eswatini,mbabane,africa,1201670.0,1180655.0,1133936.0,1099920.0,1030496.0,854011.0,598564.0,442865.0,17364.0,69.2047,1.0079,0.02
gab,146.0,gabon,libreville,africa,2388992.0,2292573.0,2028517.0,1711105.0,1272935.0,983028.0,749078.0,597192.0,267668.0,8.9252,1.0204,0.03
gmb,142.0,gambia,banjul,africa,2705992.0,2573995.0,2253133.0,1937275.0,1437539.0,1040616.0,718586.0,528731.0,10689.0,253.1567,1.0250,0.03
gnb,149.0,guinea-bissau,bissau,africa,2105566.0,2015828.0,1788919.0,1567220.0,1230849.0,973551.0,831462.0,591663.0,36125.0,58.2856,1.0218,0.03
lso,147.0,lesotho,maseru,africa,2305825.0,2254100.0,2118521.0,2022747.0,1998630.0,1798997.0,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
lbr,121.0,liberia,monrovia,africa,5302681.0,5087584.0,4612329.0,4019956.0,2895224.0,2209731.0,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
lby,107.0,libya,tripoli,africa,6812341.0,6653942.0,6192235.0,6491988.0,5154790.0,4236983.0,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
mrt,126.0,mauritania,nouakchott,africa,4736139.0,4498604.0,3946220.0,3419461.0,2695003.0,2006027.0,1506694.0,1122198.0,1030700.0,4.5951,1.0263,0.06
mus,157.0,mauritius,portlouis,africa,1299469.0,1297828.0,1293153.0,1283330.0,1215930.0,1090290.0,954865.0,830115.0,2040.0,636.9946,1.0004,0.02
myt,182.0,mayotte,mamoudzou,africa,326101.0,305587.0,249545.0,211786.0,159215.0,92659.0,52233.0,35383.0,374.0,871.9278,1.0319,0.00
nam,145.0,namibia,windhoek,africa,2567012.0,2489098.0,2282704.0,2099271.0,1819141.0,1369011.0,975994.0,754467.0,825615.0,3.1092,1.0146,0.03
cog,114.0,republicofthecongo,brazzaville,africa,5970424.0,5702174.0,5064386.0,4437884.0,3134030.0,2385435.0,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07
reu,161.0,reunion,saint-denis,africa,974052.0,957822.0,922495.0,890130.0,785424.0,658992.0,551674.0,473925.0,2511.0,387.9140,1.0082,0.01
stp,187.0,saotomeandprincipe,sãotomé,africa,227380.0,218641.0,201124.0,182138.0,143714.0,120343.0,97210.0,77583.0,964.0,235.8714,1.0192,0.00
syc,196.0,seychelles,victoria,africa,107118.0,105530.0,99240.0,92409.0,80060.0,71057.0,65290.0,54379.0,452.0,236.9867,1.0061,0.00
sle,102.0,sierraleone,freetown,africa,8605718.0,8233969.0,7314773.0,6436698.0,4584067.0,4325388.0,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11
esh,172.0,westernsahara,elaaiún,africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01

In [56]:
m[m['2022_population'].between(1_000_000, 20_000_000)]

,rank,country/territory,capital,continent,2022_population,2020_population,2015_population,2010_population,2000_population,1990_population,1980_population,1970_population,area_(km²),density_(per_km²),growth_rate,world_population_percentage
country_code,,,,,,,,,,,,,,,,
bwa,144.0,botswana,gaborone,africa,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
caf,117.0,centralafricanrepublic,bangui,africa,5579144.0,5343020.0,4819333.0,4660067.0,3759170.0,2809221.0,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
dji,160.0,djibouti,djibouti,africa,1120849.0,1090156.0,1006259.0,919199.0,742033.0,577173.0,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
gnq,152.0,equatorialguinea,malabo,africa,1674908.0,1596049.0,1346973.0,1094524.0,684977.0,465549.0,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
eri,132.0,eritrea,asmara,africa,3684032.0,3555868.0,3340006.0,3147727.0,2392880.0,2149960.0,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
swz,159.0,eswatini,mbabane,africa,1201670.0,1180655.0,1133936.0,1099920.0,1030496.0,854011.0,598564.0,442865.0,17364.0,69.2047,1.0079,0.02
gab,146.0,gabon,libreville,africa,2388992.0,2292573.0,2028517.0,1711105.0,1272935.0,983028.0,749078.0,597192.0,267668.0,8.9252,1.0204,0.03
gmb,142.0,gambia,banjul,africa,2705992.0,2573995.0,2253133.0,1937275.0,1437539.0,1040616.0,718586.0,528731.0,10689.0,253.1567,1.0250,0.03
gnb,149.0,guinea-bissau,bissau,africa,2105566.0,2015828.0,1788919.0,1567220.0,1230849.0,973551.0,831462.0,591663.0,36125.0,58.2856,1.0218,0.03
lso,147.0,lesotho,maseru,africa,2305825.0,2254100.0,2118521.0,2022747.0,1998630.0,1798997.0,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
lbr,121.0,liberia,monrovia,africa,5302681.0,5087584.0,4612329.0,4019956.0,2895224.0,2209731.0,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
lby,107.0,libya,tripoli,africa,6812341.0,6653942.0,6192235.0,6491988.0,5154790.0,4236983.0,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
mrt,126.0,mauritania,nouakchott,africa,4736139.0,4498604.0,3946220.0,3419461.0,2695003.0,2006027.0,1506694.0,1122198.0,1030700.0,4.5951,1.0263,0.06
mus,157.0,mauritius,portlouis,africa,1299469.0,1297828.0,1293153.0,1283330.0,1215930.0,1090290.0,954865.0,830115.0,2040.0,636.9946,1.0004,0.02
nam,145.0,namibia,windhoek,africa,2567012.0,2489098.0,2282704.0,2099271.0,1819141.0,1369011.0,975994.0,754467.0,825615.0,3.1092,1.0146,0.03
cog,114.0,republicofthecongo,brazzaville,africa,5970424.0,5702174.0,5064386.0,4437884.0,3134030.0,2385435.0,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07
sle,102.0,sierraleone,freetown,africa,8605718.0,8233969.0,7314773.0,6436698.0,4584067.0,4325388.0,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11